# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run master Playwright Tests

on:
  repository_dispatch:
    types: [run-playwright-master]

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Playwright Tests
        uses: actions/checkout@v3

      - name: Clone Application Code
        run: |
          git clone https://github.com/your-org/webapp.git
          cd webapp
          git checkout master

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install App and Test Dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
